## Introduction to pandas

In [5]:
import pandas as pd

In [13]:
# 2 main datatypes 

series = pd.Series(["BMW", "Toyota", "Honda"])

In [14]:
series

0       BMW
1    Toyota
2     Honda
dtype: str

In [16]:
# series = 1-dimensional (1 column)

In [17]:
colours = pd.Series(["Red", "Blue", "Orange"])
colours

0       Red
1      Blue
2    Orange
dtype: str

In [21]:
# Dataframe = 2-dimensional (2 and more columns)
car_data = pd.DataFrame({"Car make": series, "Colour": colours})
car_data

  Car make  Colour
0      BMW     Red
1   Toyota    Blue
2    Honda  Orange

In [30]:
# Importing data
car_sales = pd.read_csv("car-sales.csv")
car_sales.head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

1 - index column

ROW - axis = 0

COLUMN - axis = 1

In [37]:
# Exporting a dataframe
car_sales.to_csv("exported-car-sales.csv", index = False)

In [38]:
exported_car_sales = pd.read_csv("exported-car-sales.csv")
exported_car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00